version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws sts get-caller-identity
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381492219902.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my_private_repo .
      - docker tag my_private_repo:latest 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:latest .
      - docker tag 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:latest 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:latest
      - docker push 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"sample-app","imageUri":"%s"}]' 381492219902.dkr.ecr.us-east-1.amazonaws.com/my_private_repo:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
