version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Starting pre_build phase..."
  build:
    commands:
      - echo "Starting build phase..."
      - docker build -t my-nginx-image .
      # Generate the imagedefinitions.json file
      - echo '[{"name":"vamsee","imageUri":"your-dockerhub-username/my-nginx-image:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo "Starting post_build phase..."
      - docker images

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
